repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.12
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        files: ^(src|tests)/.*\.py$
      # Run the formatter.
      - id: ruff-format
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
    - id: pyright
      files: ^(src|tests)/.*\.py$